---
# fps: 30 = real-time, 60 = 2x, etc. One physics step per tick.
fps: 240
reset_delay: 1

steps_per_step: 4

base_env_kwargs:
  __include__: "config/env.yml"
  frames_per_step: 1

model_a:
  file: "data/PPO5-olympus/model.zip"
  mod: "stable_baselines3"
  cls: "PPO"
  name: "PPO5"
  env_kwargs: {}

model_b:
  file: "data/PPO6-olympus/model.zip"
  mod: "stable_baselines3"
  cls: "PPO"
  name: "PPO6"
  env_kwargs: {}

env_wrappers: []
