---
# 30 fps = original game display rate (physics is 25 Hz)
fps: 30
reset_delay: 1

model_file: "data/saved_models/expert_dqnfd.zip"
model_mod: "sb3_contrib"
model_cls: "QRDQN"

steps_per_step: 4

env_kwargs:
  __include__: "config/env.yml"
  frames_per_step: 1
  render_mode: "human"
  reduced_action_set: true

env_wrappers:
  - module: "qwop_python"
    cls: "VerboseWrapper"
